### ISSUE TITLE
User Rejected error when window is closed is not catchable.

### ISSUE THREAD

**Issue by ocrybit** [InternetMaximalism/webmax.js#28]
During connectToAccount(), the error from a closed window is not catchable, which stops any operations thereafter.

Fixes #

## Proposed Changes

- Combine watchWindow and eventPromiseListener into the same Promise to make both errors catchable
- Put watchWindow into eventPromiseListner and pass the reject function to watchWindow
- Don't throw an Error but reject in the watchWindow interval

**Comment by spiderings** [comment]
@ocrybit Thank you for the report and PR. 
This looks like solved by your PR https://github.com/InternetMaximalism/webmax.js/pull/29.
